apiVersion: v1
kind: Service
metadata:
  name: hub-imageinspector-ws
  namespace: hub-detect-ws
  labels:
    app: hub-imageinspector-ws
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: hub-detect-ws
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-imageinspector-ws
  namespace: hub-detect-ws
  labels:
    app: hub-imageinspector-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-imageinspector-ws
  template:
    metadata:
      labels:
        app: hub-imageinspector-ws
    spec:
      containers:
      - name: hub-imageinspector-ws-alpine
        image: blackducksoftware/hub-imageinspector-ws-alpine:1.1.2-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8080", "--current.linux.distro=alpine", "--inspector.port.alpine=8080", "--inspector.port.centos=8081", "--inspector.port.ubuntu=8082"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8080
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      - name: hub-imageinspector-ws-centos
        image: blackducksoftware/hub-imageinspector-ws-centos:1.1.2-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8081", "--current.linux.distro=centos", "--inspector.port.alpine=8080", "--inspector.port.centos=8081", "--inspector.port.ubuntu=8082"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8081
          hostPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      - name: hub-imageinspector-ws-ubuntu
        image: blackducksoftware/hub-imageinspector-ws-ubuntu:1.1.2-SNAPSHOT
        command: ["java"]
        args: ["-jar", "/opt/blackduck/hub-imageinspector-ws/hub-imageinspector-ws.jar", "--server.port=8082", "--current.linux.distro=ubuntu", "--inspector.port.alpine=8080", "--inspector.port.centos=8081", "--inspector.port.ubuntu=8082"]
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        ports:
        - containerPort: 8082
          hostPort: 8082
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: @WORKINGDIR@/shared
          type: Directory
      - name: application-config
        configMap:
          name: spring-app-config
          items:
          - key: application.properties
            path: application.properties
