apiVersion: v1
kind: Service
metadata:
  name: hub-detect-ws
  namespace: hub-detect-ws
  labels:
    app: hub-detect-ws
spec:
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: hub-detect-ws
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-detect-ws
  namespace: hub-detect-ws
  labels:
    app: hub-detect-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-detect-ws
  template:
    metadata:
      labels:
        app: hub-detect-ws
    spec:
      containers:
      - name: hub-detect-ws
        image: blackducksoftware/hub-detect-ws:0.2.0-SNAPSHOT
        volumeMounts:
        - name: blackduck-shared-dir
          mountPath: /opt/blackduck/shared
        - name: application-config
          mountPath: /opt/blackduck/hub-detect-ws/config
          readOnly: true
        ports:
        - containerPort: 8083
          hostPort: 8083
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 120
          periodSeconds: 960
          timeoutSeconds: 480
          failureThreshold: 5
        resources:
          limits:
            memory: 2Gi
      volumes:
      - name: blackduck-shared-dir
        hostPath:
          path: @WORKINGDIR@/shared
          type: Directory
      - name: application-config
        configMap:
          name: spring-app-config
          items:
          - key: application.properties
            path: application.properties

